# Generated by Django 2.2.2 on 2019-06-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.SmallIntegerField()),
                ('user_id', models.SmallIntegerField()),
                ('comment', models.TextField(max_length=100)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('D', 'Dunia'), ('T', 'Tanzania'), ('M', 'Mkoa'), ('W', 'Wilaya'), ('K', 'Kata')], max_length=1)),
                ('source', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('published_date', models.DateField()),
                ('start_date', models.PositiveSmallIntegerField()),
                ('end_date', models.PositiveSmallIntegerField()),
                ('cvs_filePath', models.FileField(upload_to='', verbose_name='data file')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('time_posted', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('scope', models.SmallIntegerField()),
                ('sector', models.CharField(max_length=20)),
                ('dataset_id', models.SmallIntegerField()),
                ('user_id', models.SmallIntegerField()),
                ('post_evaluation', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taswira.Question')),
            ],
        ),
    ]
