# Generated by Django 2.2.2 on 2019-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taswira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cvs_filePath',
            field=models.FileField(default='lija', upload_to='', verbose_name='data file'),
            preserve_default=False,
        ),
    ]
