# Generated by Django 2.2.2 on 2019-06-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taswira', '0002_question_cvs_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cvs_filePath',
        ),
    ]
