# Generated by Django 2.2.2 on 2019-06-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taswira', '0003_remove_question_cvs_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('cvs', models.FileField(upload_to='', verbose_name='post')),
            ],
        ),
    ]
