# Generated by Django 2.2.2 on 2019-06-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taswira', '0004_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='cvs',
        ),
        migrations.AddField(
            model_name='post1',
            name='cvs_path',
            field=models.FileField(default='lija', upload_to='static/taswira/dataset/'),
            preserve_default=False,
        ),
    ]
